# Generated by Django 5.2.13 on 2026-05-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_friendsship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendsShip',
            new_name='Friendship',
        ),
    ]
